PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX linkml: <https://w3id.org/linkml/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select
distinct ?slot ?l
where {
    graph <https://w3id.org/nmdc/nmdc>
    {
        ?slot a linkml:SlotDefinition .
        optional {
            ?slot rdfs:label ?l
        }     minus {
            ?slot skos:definition ?d
        }
    }
    minus {
        graph <mongodb://mongo-loadbalancer.nmdc.production.svc.spin.nersc.gov:27017>
        {
            ?s ?slot ?o
        }
    }
}
order by ?slot