# LinkML Linter Configuration for NMDC Schema
#
# This configuration includes all 13 available LinkML linting rules,
# set to either "error" or "disabled" (no warnings).
#
# Rule documentation: https://linkml.io/linkml/schemas/linter.html

extends: recommended

rules:
  # ==========================================
  # ENABLED RULES (error level)
  # ==========================================

  # Validate that slot_usage references valid slots
  no_invalid_slot_usage:
    level: error

  # Prefer xsd:integer over xsd:int
  no_xsd_int_type:
    level: error

  # Check that all slots referenced by classes are declared
  no_undeclared_slots:
    level: error

  # Check that all ranges reference valid types/enums/classes
  no_undeclared_ranges:
    level: error

  # Ensure at most one identifier slot per class
  one_identifier_per_class:
    level: error

  # Ensure at most one key slot per class
  one_key_per_class:
    level: error

  # Validate type definitions (base and uri for root types)
  root_type_checks:
    level: error

  # Require exactly one tree_root class
  # DISABLED: Only nmdc.yaml has the tree_root class (Database)
  # Use .linkmllint-root.yaml for nmdc.yaml and nmdc_materialized_patterns.yaml
  tree_root_class:
    level: disabled

  # ==========================================
  # DISABLED RULES
  # ==========================================

  # Require recommended metamodel slots (like 'description')
  # DISABLED: Many elements lack descriptions; would require significant documentation effort
  recommended:
    level: disabled

  # Enforce standard naming conventions (UpperCamel for classes/enums, snake_case for slots)
  # DISABLED: MIxS uses snake_case enums (e.g., arch_struc_enum) and slots with spaces
  standard_naming:
    level: disabled

  # Check prefix mappings against prefixmaps standards
  # DISABLED: NMDC intentionally uses bioregistry.io prefixes which differ from
  # the default prefixmaps contexts that prefer identifiers.org
  canonical_prefixes:
    level: disabled

  # Require titles on all schema elements
  # DISABLED: Would require adding titles to many existing elements
  no_empty_title:
    level: disabled

  # Enforce consistent permissible value formatting
  # DISABLED: NMDC uses scientific terminology as PV keys (e.g., DNA, Orbitrap, C18)
  permissible_values_format:
    level: disabled
