# LinkML Linter Configuration for NMDC Schema
# Based on the recommended ruleset with customizations for NMDC-specific needs
# See: https://linkml.io/linkml/schemas/linter.html

extends: recommended

rules:
  # Recommended slots (like 'description') should be present
  # Set to warning initially to see what we're dealing with
  # Can escalate to error later once we've addressed the issues
  recommended:
    level: warning
    # Exclude enums from description requirement for now
    # Many enums are self-explanatory from their permissible values
    exclude_type:
      - enum_definition
    # Specific classes/slots to exclude (add as needed)
    exclude: []

  # Enforce standard naming conventions
  # Classes: UpperCamelCase, Slots: snake_case, Enums: UpperCamelCase
  standard_naming:
    level: warning
    # Exclude permissible values from naming checks
    # Many PVs are domain-specific terms that shouldn't be snake_cased
    exclude_type:
      - permissible_value

  # Validate that slot_usage references valid slots
  no_invalid_slot_usage:
    level: error

  # Prefer xsd:integer over xsd:int
  no_xsd_int_type:
    level: warning

  # Check prefix mappings against prefixmaps standards
  canonical_prefixes:
    level: warning
    prefixmaps_contexts:
      - merged
