# LinkML Linter Configuration for NMDC Schema
# All rules enabled with no exclusions to get full visibility
# See: https://linkml.io/linkml/schemas/linter.html

extends: recommended

rules:
  # Require recommended metamodel slots (like 'description')
  recommended:
    level: warning

  # Enforce standard naming conventions
  # Classes: UpperCamelCase, Slots: snake_case, Enums: UpperCamelCase
  standard_naming:
    level: warning

  # Validate that slot_usage references valid slots
  no_invalid_slot_usage:
    level: error

  # Prefer xsd:integer over xsd:int
  no_xsd_int_type:
    level: warning

  # Check prefix mappings against prefixmaps standards
  canonical_prefixes:
    level: warning
    prefixmaps_contexts:
      - merged

  # Additional rules not in "recommended" preset:

  # Require titles on all schema elements
  no_empty_title:
    level: warning

  # Enforce consistent permissible value formatting
  permissible_values_format:
    level: warning
    format: snake

  # Require exactly one tree_root class
  tree_root_class:
    level: warning
    root_class_name: Database
    validate_existing_class_name: true
