# LinkML Linter Configuration for NMDC Schema
# All rules enabled with all default values explicitly stated
# See: https://linkml.io/linkml/schemas/linter.html
#
# Configuration philosophy:
# - All 7 available rules enabled (no masking)
# - All default values explicitly shown and commented
# - Full visibility into schema quality issues

extends: recommended

rules:
  # ==========================================
  # Rules included in "recommended" preset
  # ==========================================

  # Require recommended metamodel slots (like 'description')
  recommended:
    level: warning
    # include: []  # default: check all elements
    # exclude: []  # default: no exclusions
    # exclude_type: []  # default: check all types (class_definition, slot_definition, enum_definition, permissible_value)

  # Enforce standard naming conventions
  standard_naming:
    level: warning
    # class_pattern: uppercamel  # default: uppercamel pattern ([A-Z][a-zA-Z0-9]+)
    # slot_pattern: snake  # default: snake pattern ([a-z][_a-z0-9]+)
    permissible_values_upper_case: false  # default: false (snake_case for PVs, not UPPER_SNAKE)
    exclude_type:
      - permissible_value  # Exclude PVs - they use scientific terminology (e.g., "DNA", "Orbitrap", "C18")

  # Validate that slot_usage references valid slots (CRITICAL - only error-level rule)
  no_invalid_slot_usage:
    level: error

  # Prefer xsd:integer over xsd:int
  no_xsd_int_type:
    level: warning

  # Check prefix mappings against prefixmaps standards
  canonical_prefixes:
    level: warning
    prefixmaps_contexts:
      - merged  # default: use merged context (combined from all sources)

  # ==========================================
  # Additional rules (not in "recommended")
  # ==========================================

  # Require titles on all schema elements
  no_empty_title:
    level: warning
    # exclude_type: []  # default: check all types (class_definition, slot_definition, enum_definition, permissible_value)

  # Enforce consistent permissible value formatting
  # DISABLED: NMDC uses scientific terminology as PV keys (e.g., "DNA", "Orbitrap", "C18")
  # These terms should be preserved as-is, not forced to snake_case
  permissible_values_format:
    level: disabled
    # format: snake  # default in base config: uppersnake; options: snake, uppersnake, camel, uppercamel, kebab, or custom regex

  # Require exactly one tree_root class
  tree_root_class:
    level: warning
    root_class_name: Database  # default: Container
    validate_existing_class_name: true  # default: false
