# LinkML Linter Configuration for Root Schema Files
#
# Use this config for:
# - src/schema/nmdc.yaml (defines Database tree_root)
# - nmdc_schema/nmdc_materialized_patterns.yaml (materialized schema)
#
# Same as .linkmllint.yaml but with tree_root_class enabled.
#
# Rule documentation: https://linkml.io/linkml/schemas/linter.html

extends: recommended

rules:
  # ==========================================
  # ENABLED RULES (error level)
  # ==========================================

  # Validate that slot_usage references valid slots
  no_invalid_slot_usage:
    level: error

  # Prefer xsd:integer over xsd:int
  no_xsd_int_type:
    level: error

  # Check that all slots referenced by classes are declared
  no_undeclared_slots:
    level: error

  # Check that all ranges reference valid types/enums/classes
  no_undeclared_ranges:
    level: error

  # Ensure at most one identifier slot per class
  one_identifier_per_class:
    level: error

  # Ensure at most one key slot per class
  one_key_per_class:
    level: error

  # Validate type definitions (base and uri for root types)
  root_type_checks:
    level: error

  # Require exactly one tree_root class named Database
  tree_root_class:
    level: error
    root_class_name: Database
    validate_existing_class_name: true

  # ==========================================
  # DISABLED RULES
  # ==========================================

  # Require recommended metamodel slots (like 'description')
  recommended:
    level: disabled

  # Enforce standard naming conventions
  standard_naming:
    level: disabled

  # Check prefix mappings against prefixmaps standards
  canonical_prefixes:
    level: disabled

  # Require titles on all schema elements
  no_empty_title:
    level: disabled

  # Enforce consistent permissible value formatting
  permissible_values_format:
    level: disabled
