"""Report tracked files under ``assets/`` that nothing in the repo refers to.

Two findings, from one pass over the tracked asset list.

**Unreferenced.** A file under ``assets/`` that no Makefile, workflow, test, script,
or committed document names. Nothing builds it and nothing consumes it, so it cannot
go stale loudly; it goes stale silently. ``assets/`` is no longer the default output
destination (see the policy table in ``CONTRIBUTING.md``), so an unreferenced file
there is a retirement candidate rather than a normal state.

**Names a deprecated element.** A file under ``assets/`` that mentions a class, slot,
enum, or type defined in ``src/schema/deprecated.yaml``. The two-release deprecation
process in ``src/docs/schema_element_deprecation_guide.md`` strips references out of
the schema source; until 2026-08 it said nothing about ``assets/``, so mapping files
kept naming elements the schema no longer exposes.

The two findings interact, which is the reason they share a script. An asset that is
both unreferenced and names a deprecated element needs no remapping decision: nothing
reads it, so it can be deleted. One that is referenced needs the reference fixed or
regenerated instead.

Usage::

    poetry run python src/scripts/report_asset_usage.py
    poetry run python src/scripts/report_asset_usage.py --format tsv

Report-only; the exit status is 0 unless the script itself fails. The gate is
``tests/test_no_new_unreferenced_assets.py``, which ratchets the unreferenced set
against a reviewed allowlist.
"""

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import click
import yaml

ASSETS_DIR = "assets"
DEPRECATED_SCHEMA = "src/schema/deprecated.yaml"

# Directories that are generated, vendored, or themselves the thing being audited.
# A hit inside any of these is not evidence that anything consumes the asset.
SEARCH_EXCLUDED_DIRS = frozenset(
    {
        ".git",
        ".venv",
        "__pycache__",
        ASSETS_DIR,
        "docs",  # generated by `make gendoc`
        "project",  # generated by `make gen-project`, and gitignored
        "local",  # gitignored scratch
        "site",
        "node_modules",
    }
)

# Suffixes worth searching for a filename reference. Binary and generated payloads are
# skipped: a match inside one is a data coincidence, not a consumer.
SEARCHABLE_SUFFIXES = frozenset(
    {
        "",
        ".cfg",
        ".ini",
        ".js",
        ".json",
        ".jsonld",
        ".Makefile",
        ".md",
        ".py",
        ".sh",
        ".toml",
        ".txt",
        ".yaml",
        ".yml",
        ".ru",
        ".yq",
    }
)

# This audit and its ratchet name assets only to account for them. Counting those
# mentions as references would make every allowlisted file look consumed, which is how
# the first draft of this script reported zero orphans.
AUDIT_FILES = frozenset(
    {
        "src/scripts/report_asset_usage.py",
        "tests/test_no_new_unreferenced_assets.py",
        "src/docs/asset-lifecycle.md",
    }
)


@dataclass(frozen=True, order=True)
class AssetFinding:
    """One tracked asset, with what refers to it and which deprecated elements it names."""

    path: str
    referenced_by: tuple
    deprecated_elements: tuple

    @property
    def is_unreferenced(self):
        return not self.referenced_by


def _run_git(args, repo_root):
    """Run a git command in ``repo_root`` and return its stdout."""
    return subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def tracked_assets(repo_root):
    """Every file tracked by git under ``assets/``, as repo-relative POSIX paths."""
    output = _run_git(["ls-files", ASSETS_DIR], repo_root)
    return sorted(line for line in output.splitlines() if line)


def deprecated_element_names(repo_root):
    """Every element name defined in ``deprecated.yaml``.

    Covers classes, slots, enums, types, and subsets. Permissible values are not
    included: the schema has no way to retire a permissible value into
    ``deprecated.yaml`` (see the deprecation guide), so there is nothing to read.
    """
    schema = yaml.safe_load((repo_root / DEPRECATED_SCHEMA).read_text())
    names = set()
    for section in ("classes", "slots", "enums", "types", "subsets"):
        names.update(schema.get(section) or {})
    return names


def _searchable_files(repo_root):
    """Repo files that could plausibly name an asset, excluding generated trees."""
    for path in repo_root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(repo_root)
        if SEARCH_EXCLUDED_DIRS.intersection(relative.parts):
            continue
        if relative.as_posix() in AUDIT_FILES:
            continue
        if path.suffix not in SEARCHABLE_SUFFIXES:
            continue
        yield path


def _read_text(path):
    """Read a file as text, tolerating stray bytes; empty string if unreadable."""
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def find_asset_findings(repo_root):
    """Build one :class:`AssetFinding` per tracked asset.

    An asset counts as referenced if any searchable file outside ``assets/`` contains
    either its repo-relative path or its bare filename. The bare filename is included
    because Makefiles and scripts often build the path from a variable, so requiring
    the full path would report false orphans.
    """
    repo_root = Path(repo_root)
    assets = tracked_assets(repo_root)
    deprecated = deprecated_element_names(repo_root)

    corpus = {path: _read_text(path) for path in _searchable_files(repo_root)}

    element_patterns = {
        name: re.compile(rf"(?<![0-9A-Za-z_]){re.escape(name)}(?![0-9A-Za-z_])")
        for name in deprecated
    }

    findings = []
    for asset in assets:
        basename = Path(asset).name
        referenced_by = sorted(
            str(path.relative_to(repo_root))
            for path, text in corpus.items()
            if asset in text or basename in text
        )
        asset_text = _read_text(repo_root / asset)
        named = tuple(
            sorted(
                name
                for name, pattern in element_patterns.items()
                if pattern.search(asset_text)
            )
        )
        findings.append(AssetFinding(asset, tuple(referenced_by), named))
    return findings


def _emit_text(findings):
    unreferenced = [f for f in findings if f.is_unreferenced]
    naming_deprecated = [f for f in findings if f.deprecated_elements]
    both = [f for f in unreferenced if f.deprecated_elements]

    click.echo(
        f"{len(findings)} tracked files under {ASSETS_DIR}/; "
        f"{len(unreferenced)} referenced nowhere; "
        f"{len(naming_deprecated)} naming a deprecated element."
    )

    click.echo("\nReferenced nowhere in the repo:")
    for finding in unreferenced or ():
        click.echo(f"  {finding.path}")
    if not unreferenced:
        click.echo("  (none)")

    click.echo(f"\nNaming an element defined in {DEPRECATED_SCHEMA}:")
    for finding in naming_deprecated or ():
        click.echo(f"  {finding.path}: {', '.join(finding.deprecated_elements)}")
    if not naming_deprecated:
        click.echo("  (none)")

    click.echo("\nBoth (deletable without a remapping decision, nothing reads them):")
    for finding in both or ():
        click.echo(f"  {finding.path}")
    if not both:
        click.echo("  (none)")


def _emit_tsv(findings):
    click.echo("asset\treferenced_by\tdeprecated_elements_named")
    for finding in findings:
        click.echo(
            "\t".join(
                [
                    finding.path,
                    "|".join(finding.referenced_by),
                    "|".join(finding.deprecated_elements),
                ]
            )
        )


@click.command()
@click.option(
    "--repo-root",
    default=".",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    help="Repository root to audit.",
)
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["text", "tsv"]),
    default="text",
    help="text for a human-readable report, tsv for one row per asset.",
)
def report(repo_root, output_format):
    """Report unreferenced assets and assets naming deprecated schema elements."""
    findings = find_asset_findings(repo_root)
    if output_format == "tsv":
        _emit_tsv(findings)
    else:
        _emit_text(findings)


if __name__ == "__main__":
    sys.exit(report())
