"""Enforce attribution spelling in the src/schema/*.yaml source files directly.

Deliberately do not read nmdc_schema/nmdc_materialized_patterns.yaml, the
generated artifact other tests load via SCHEMA_FILE. This rule concerns how
humans write source values: the generator normalizes and expands values, so
testing its artifact would not catch what an author actually typed.

src/schema/mixs.yaml is generated by the MIxS customization pipeline rather
than hand-edited. Scan it too (its two current values conform), but fix that
pipeline, rather than hand-editing the file, if it fails in the future.
"""

from pathlib import Path
import re

import yaml


ATTRIBUTION_KEYS = {"created_by", "modified_by", "contributors"}
ORCID_PATTERN = re.compile(
    r"(?:orcid:|https://orcid\.org/)[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]"
)


def attribution_values(node):
    """Yield attribution keys and values from mappings and lists at any depth."""
    if isinstance(node, dict):
        for key, value in node.items():
            if key in ATTRIBUTION_KEYS:
                for item in value if isinstance(value, list) else [value]:
                    yield key, item
            yield from attribution_values(value)
    elif isinstance(node, list):
        for item in node:
            yield from attribution_values(item)


def test_attribution_metaslots():
    repository_root = Path(__file__).resolve().parents[1]
    offending_values = []
    for path in sorted((repository_root / "src" / "schema").glob("*.yaml")):
        with path.open(encoding="utf-8") as source:
            schema = yaml.safe_load(source)
        for key, value in attribution_values(schema):
            if not isinstance(value, str) or ORCID_PATTERN.fullmatch(value) is None:
                offending_values.append((path.relative_to(repository_root), key, value))

    assert not offending_values, (
        "Attribution values must use canonical lowercase orcid: or https://orcid.org/ "
        "followed by an ORCID identifier of the form NNNN-NNNN-NNNN-NNNC "
        "(N is an ASCII digit; C is an ASCII digit or uppercase X).\n"
        + "\n".join(
            f"{path}: {key}: {value!r}" for path, key, value in offending_values
        )
    )
