services:

  mongo-init:
    image: mongo:8.0.4
    volumes:
      - .docker/wait-for-it.sh:/wait-for-it.sh:ro
      - .docker/mongo_init/initialize_replica_set.sh:/initialize_replica_set.sh:ro
    depends_on:
      mongo: { condition: service_started }
    entrypoint: /bin/bash /wait-for-it.sh --host=mongo --port=27017 --timeout=20 -- /bin/sh /initialize_replica_set.sh mongo 27017 admin root

  mongo:
    image: mongo:8.0.4
    ports:
      - "${DEV_STACK_HOST_MACHINE_PORT_MONGO}:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/keyFile"]
    volumes:
      - mongo_data:/data/db
      - ./.docker/mongoKeyFile:/keyFile:ro

volumes:
  mongo_data:
    driver: local

name: nmdc-schema-migrator-dev