@startuml
skinparam nodesep 10
class "TextValue"
class "Study"
class "Solution" {
    {field} "type": "uriorcurie" [req]
}
class "QuantityValue"
class "PortionOfSubstance" {
    {field} "sample_state_information": "SampleStateEnum" [opt]
    {field} "substance_role": "SubstanceRoleEnum" [opt]
    {field} "type": "uriorcurie" [req]
}
class "ChromatographicSeparationProcess" {
    {field} "chromatographic_category": "ChromatographicCategoryEnum" [opt]
    {field} "stationary_phase": "StationaryPhaseEnum" [opt]
    {field} "id": "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
class "DissolvingProcess"
"Solution" *--> "0..1" "QuantityValue" : "volume"
"Solution" *--> "0..*" "PortionOfSubstance" : "substances_used"
"ChromatographicSeparationProcess" *--> "0..*" "Solution" : "ordered_mobile_phases"
"DissolvingProcess" *--> "1" "Solution" : "solvent"
class "Protocol"
class "ProcessedSample"
class "ChemicalEntity"
class "Extraction"
class "ChemicalConversionProcess"
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "volume"
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "source_concentration"
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "mass"
"PortionOfSubstance" --> "0..1" "ChemicalEntity" : "known_as"
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "final_concentration"
"DissolvingProcess" *--> "0..1" "PortionOfSubstance" : "solubilizing_agent"
"Extraction" *--> "0..*" "PortionOfSubstance" : "substances_used"
"ChemicalConversionProcess" *--> "0..*" "PortionOfSubstance" : "substances_used"
class "PersonValue"
abstract "NamedThing"
class "MaterialProcessing"
class "MassSpectrometry" {
    {field} "acquisition_category": "AcquisitionCategoryEnum" [opt]
    {field} "acquisition_strategy": "AcquisitionStrategyEnum" [opt]
    {field} "resolution_category": "ResolutionCategoryEnum" [opt]
    {field} "mass_analyzer": "MassAnalyzerEnum" [opt]
    {field} "ionization_source": "IonizationSourceEnum" [opt]
    {field} "mass_spectrum_collection_mode": "MassSpectrumCollectionModeEnum" [opt]
    {field} "polarity_mode": "PolarityModeEnum" [opt]
    {field} "id": "uriorcurie" [req]
    {field} "add_date"(i): "string" [opt]
    {field} "analyte_category"(i): "AnalyteCategoryEnum" [req]
    {field} "gold_sequencing_project_identifiers"(i): "external_identifier" [0..*]
    {field} "insdc_bioproject_identifiers"(i): "external_identifier" [0..*]
    {field} "insdc_experiment_identifiers"(i): "external_identifier" [0..*]
    {field} "mod_date"(i): "string" [opt]
    {field} "ncbi_project_name"(i): "string" [opt]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
abstract "FluidHandling" {
    {field} "id"(i): "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
abstract "DataGeneration"
"MassSpectrometry" --> "0..1" "FluidHandling" : "eluent_introduction"
"DataGeneration" ^-- "MassSpectrometry"
class "Instrument"
class "DirectInfusionProcess"
"FluidHandling" ^-- "DirectInfusionProcess"
"FluidHandling" ^-- "ChromatographicSeparationProcess"
"MaterialProcessing" ^-- "FluidHandling"
class "FailureCategorization"
class "DataObject"
"ChromatographicSeparationProcess" *--> "0..1" "QuantityValue" : "temperature"
"ChromatographicSeparationProcess" --> "0..1" "DataObject" : "has_calibration"
@enduml
