@startuml
skinparam nodesep 10
class "WorkflowExecution"
class "WorkflowChain"
class "TextValue"
class "SubSamplingProcess"
class "Study"
class "SolutionComponent" {
    {field} "compound": "string" [req]
    {field} "type": "uriorcurie" [req]
}
class "QuantityValue"
class "Solution" {
    {field} "type": "uriorcurie" [req]
}
"SolutionComponent" *--> "0..1" "QuantityValue" : "concentration"
"Solution" *--> "1..*" "SolutionComponent" : "has_solution_components"
class "Extraction"
class "ChromatographicSeparationProcess" {
    {field} "chromatographic_category": "ChromatographicCategoryEnum" [opt]
    {field} "stationary_phase": "StationaryPhaseEnum" [opt]
    {field} "id": "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
class "DissolvingProcess"
"Solution" *--> "0..1" "QuantityValue" : "volume"
"Extraction" *--> "0..1" "Solution" : "extractant"
"ChromatographicSeparationProcess" *--> "0..*" "Solution" : "ordered_mobile_phases"
"DissolvingProcess" *--> "1" "Solution" : "solvent"
class "ProtocolExecution"
class "Protocol"
class "ProcessedSample"
class "Pooling"
abstract "PlannedProcess" {
    {field} "processing_institution": "ProcessingInstitutionEnum" [opt]
    {field} "start_date": "string" [opt]
    {field} "end_date": "string" [opt]
    {field} "qc_status": "StatusEnum" [opt]
    {field} "qc_comment": "string" [opt]
    {field} "id"(i): "uriorcurie" [req]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
class "FailureCategorization"
class "Instrument"
abstract "NamedThing"
class "Database"
class "MaterialProcessing" {
    {field} "id": "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
abstract "DataGeneration"
class "CollectingBiosamplesFromSite"
"PlannedProcess" *--> "0..*" "FailureCategorization" : "has_failure_categorization"
"PlannedProcess" *--> "0..1" "Protocol" : "protocol_link"
"PlannedProcess" --> "0..*" "Instrument" : "instrument_used"
"PlannedProcess" --> "0..*" "NamedThing" : "has_output"
"PlannedProcess" --> "0..*" "NamedThing" : "has_input"
"ProtocolExecution" --> "1..*" "PlannedProcess" : "has_process_parts"
"Database" *--> "0..*" "PlannedProcess" : "planned_process_set"
"PlannedProcess" ^-- "WorkflowExecution"
"PlannedProcess" ^-- "WorkflowChain"
"PlannedProcess" ^-- "ProtocolExecution"
"PlannedProcess" ^-- "MaterialProcessing"
"PlannedProcess" ^-- "DataGeneration"
"PlannedProcess" ^-- "CollectingBiosamplesFromSite"
"NamedThing" ^-- "PlannedProcess"
class "PersonValue"
class "MixingProcess"
class "LibraryPreparation"
abstract "FluidHandling" {
    {field} "id"(i): "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
class "FiltrationProcess"
class "ChemicalConversionProcess"
"MaterialProcessing" --> "0..*" "ProcessedSample" : "has_output"
"MaterialProcessing" --> "0..*" "NamedThing" : "has_input"
"MaterialProcessing" ^-- "SubSamplingProcess"
"MaterialProcessing" ^-- "Pooling"
"MaterialProcessing" ^-- "MixingProcess"
"MaterialProcessing" ^-- "LibraryPreparation"
"MaterialProcessing" ^-- "FluidHandling"
"MaterialProcessing" ^-- "FiltrationProcess"
"MaterialProcessing" ^-- "Extraction"
"MaterialProcessing" ^-- "DissolvingProcess"
"MaterialProcessing" ^-- "ChemicalConversionProcess"
class "MassSpectrometry" {
    {field} "acquisition_category": "AcquisitionCategoryEnum" [opt]
    {field} "acquisition_strategy": "AcquisitionStrategyEnum" [opt]
    {field} "resolution_category": "ResolutionCategoryEnum" [opt]
    {field} "mass_analyzer": "MassAnalyzerEnum" [opt]
    {field} "ionization_source": "IonizationSourceEnum" [opt]
    {field} "mass_spectrum_collection_mode": "MassSpectrumCollectionModeEnum" [opt]
    {field} "polarity_mode": "PolarityModeEnum" [opt]
    {field} "id": "uriorcurie" [req]
    {field} "add_date"(i): "string" [opt]
    {field} "analyte_category"(i): "AnalyteCategoryEnum" [req]
    {field} "gold_sequencing_project_identifiers"(i): "external_identifier" [0..*]
    {field} "insdc_bioproject_identifiers"(i): "external_identifier" [0..*]
    {field} "insdc_experiment_identifiers"(i): "external_identifier" [0..*]
    {field} "mod_date"(i): "string" [opt]
    {field} "ncbi_project_name"(i): "string" [opt]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
"MassSpectrometry" --> "0..1" "FluidHandling" : "eluent_introduction"
"DataGeneration" ^-- "MassSpectrometry"
class "DirectInfusionProcess"
"FluidHandling" ^-- "DirectInfusionProcess"
"FluidHandling" ^-- "ChromatographicSeparationProcess"
class "DataObject"
"ChromatographicSeparationProcess" *--> "0..1" "QuantityValue" : "temperature"
"ChromatographicSeparationProcess" --> "0..1" "DataObject" : "has_calibration"
@enduml
