erDiagram
SubstanceEntity {
    stringList alternative_names  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
Solution {
    uriorcurie type  
}
QuantityValue {
    float has_maximum_numeric_value  
    float has_minimum_numeric_value  
    double has_numeric_value  
    unit has_unit  
    string has_raw_value  
    uriorcurie type  
}
PortionOfSubstance {
    SampleStateEnum sample_state_information  
    SubstanceRoleEnum substance_role  
    uriorcurie type  
}
MetaboliteQuantification {
    uriorcurieList alternative_identifiers  
    float highest_similarity_score  
    uriorcurie type  
}
MassSpectrometry {
    AcquisitionCategoryEnum acquisition_category  
    AcquisitionStrategyEnum acquisition_strategy  
    ResolutionCategoryEnum resolution_category  
    MassAnalyzerEnum mass_analyzer  
    IonizationSourceEnum ionization_source  
    MassSpectrumCollectionModeEnum mass_spectrum_collection_mode  
    PolarityModeEnum polarity_mode  
    string add_date  
    AnalyteCategoryEnum analyte_category  
    external_identifierList gold_sequencing_project_identifiers  
    external_identifierList insdc_bioproject_identifiers  
    external_identifierList insdc_experiment_identifiers  
    string mod_date  
    string ncbi_project_name  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
FailureCategorization {
    FailureWhatEnum qc_failure_what  
    FailureWhereEnum qc_failure_where  
}
Protocol {
    string url  
    string name  
    uriorcurie type  
}
TextValue {
    language_code language  
    string has_raw_value  
    uriorcurie type  
}
PersonValue {
    string email  
    string name  
    string orcid  
    string profile_image_url  
    stringList websites  
    string has_raw_value  
    uriorcurie type  
}
FluidHandling {
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
Extraction {
    ExtractionTargetEnum extraction_target  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
DissolvingProcess {
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
ChromatographicSeparationProcess {
    ChromatographicCategoryEnum chromatographic_category  
    StationaryPhaseEnum stationary_phase  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
ChemicalEntity {
    string chemical_formula  
    string inchi  
    string inchi_key  
    stringList smiles  
    stringList alternative_names  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
ChemicalConversionProcess {
    ChemicalConversionCategoryEnum chemical_conversion_category  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}

Solution ||--}o PortionOfSubstance : "substances_used"
Solution ||--|o QuantityValue : "volume"
QuantityValue ||--|o WorkflowExecution : "was_generated_by"
PortionOfSubstance ||--|o QuantityValue : "final_concentration"
PortionOfSubstance ||--|o SubstanceEntity : "known_as"
PortionOfSubstance ||--|o QuantityValue : "mass"
PortionOfSubstance ||--|o QuantityValue : "source_concentration"
PortionOfSubstance ||--|o QuantityValue : "volume"
MetaboliteQuantification ||--|o ChemicalEntity : "metabolite_quantified"
MassSpectrometry ||--|o FluidHandling : "eluent_introduction"
MassSpectrometry ||--}| Study : "associated_studies"
MassSpectrometry ||--}o DataGeneration : "part_of"
MassSpectrometry ||--|o PersonValue : "principal_investigator"
MassSpectrometry ||--|o TextValue : "target_gene"
MassSpectrometry ||--|o TextValue : "target_subfragment"
MassSpectrometry ||--}| NamedThing : "has_input"
MassSpectrometry ||--}o DataObject : "has_output"
MassSpectrometry ||--}o Instrument : "instrument_used"
MassSpectrometry ||--|o Protocol : "protocol_link"
MassSpectrometry ||--}o FailureCategorization : "has_failure_categorization"
TextValue ||--|o WorkflowExecution : "was_generated_by"
PersonValue ||--|o WorkflowExecution : "was_generated_by"
FluidHandling ||--}o NamedThing : "has_input"
FluidHandling ||--}o ProcessedSample : "has_output"
FluidHandling ||--}o Instrument : "instrument_used"
FluidHandling ||--|o Protocol : "protocol_link"
FluidHandling ||--}o FailureCategorization : "has_failure_categorization"
Extraction ||--}o PortionOfSubstance : "substances_used"
Extraction ||--|o QuantityValue : "input_mass"
Extraction ||--|o QuantityValue : "volume"
Extraction ||--}o NamedThing : "has_input"
Extraction ||--}| ProcessedSample : "has_output"
Extraction ||--}o Instrument : "instrument_used"
Extraction ||--|o Protocol : "protocol_link"
Extraction ||--}o FailureCategorization : "has_failure_categorization"
DissolvingProcess ||--|| Solution : "solvent"
DissolvingProcess ||--|o PortionOfSubstance : "solubilizing_agent"
DissolvingProcess ||--|o QuantityValue : "duration"
DissolvingProcess ||--|o QuantityValue : "temperature"
DissolvingProcess ||--}o NamedThing : "has_input"
DissolvingProcess ||--}o ProcessedSample : "has_output"
DissolvingProcess ||--}o Instrument : "instrument_used"
DissolvingProcess ||--|o Protocol : "protocol_link"
DissolvingProcess ||--}o FailureCategorization : "has_failure_categorization"
ChromatographicSeparationProcess ||--|o DataObject : "has_calibration"
ChromatographicSeparationProcess ||--}o Solution : "ordered_mobile_phases"
ChromatographicSeparationProcess ||--|o QuantityValue : "temperature"
ChromatographicSeparationProcess ||--}o NamedThing : "has_input"
ChromatographicSeparationProcess ||--}o ProcessedSample : "has_output"
ChromatographicSeparationProcess ||--}o Instrument : "instrument_used"
ChromatographicSeparationProcess ||--|o Protocol : "protocol_link"
ChromatographicSeparationProcess ||--}o FailureCategorization : "has_failure_categorization"
ChemicalConversionProcess ||--|o QuantityValue : "duration"
ChemicalConversionProcess ||--|o QuantityValue : "temperature"
ChemicalConversionProcess ||--}o PortionOfSubstance : "substances_used"
ChemicalConversionProcess ||--|o QuantityValue : "substances_volume"
ChemicalConversionProcess ||--}o NamedThing : "has_input"
ChemicalConversionProcess ||--}o ProcessedSample : "has_output"
ChemicalConversionProcess ||--}o Instrument : "instrument_used"
ChemicalConversionProcess ||--|o Protocol : "protocol_link"
ChemicalConversionProcess ||--}o FailureCategorization : "has_failure_categorization"

