erDiagram
PortionOfSubstance {
    SampleStateEnum sample_state_information  
    SubstanceRoleEnum substance_role  
    uriorcurie type  
}
QuantityValue {
    float has_maximum_numeric_value  
    float has_minimum_numeric_value  
    double has_numeric_value  
    unit has_unit  
    string has_raw_value  
    uriorcurie type  
}
MobilePhaseSegment {
    uriorcurie type  
}
Extraction {
    ExtractionTargetEnum extraction_target  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
FailureCategorization {
    FailureWhatEnum qc_failure_what  
    FailureWhereEnum qc_failure_where  
}
Protocol {
    string url  
    string name  
    uriorcurie type  
}
DissolvingProcess {
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
ChromatographicSeparationProcess {
    string has_calibration  
    ChromatographicCategoryEnum chromatographic_category  
    StationaryPhaseEnum stationary_phase  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
ChemicalEntity {
    stringList alternative_names  
    string chemical_formula  
    string inchi  
    string inchi_key  
    stringList smiles  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
ChemicalConversionProcess {
    ChemicalConversionCategoryEnum chemical_conversion_category  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}

PortionOfSubstance ||--|o QuantityValue : "final_concentration"
PortionOfSubstance ||--|o ChemicalEntity : "known_as"
PortionOfSubstance ||--|o QuantityValue : "mass"
PortionOfSubstance ||--|o QuantityValue : "source_concentration"
PortionOfSubstance ||--|o QuantityValue : "volume"
QuantityValue ||--|o WorkflowExecution : "was_generated_by"
MobilePhaseSegment ||--|o QuantityValue : "duration"
MobilePhaseSegment ||--}o PortionOfSubstance : "substances_used"
MobilePhaseSegment ||--|o QuantityValue : "volume"
Extraction ||--}o PortionOfSubstance : "substances_used"
Extraction ||--|o QuantityValue : "input_mass"
Extraction ||--|o QuantityValue : "volume"
Extraction ||--}o NamedThing : "has_input"
Extraction ||--}| ProcessedSample : "has_output"
Extraction ||--}o Instrument : "instrument_used"
Extraction ||--|o Protocol : "protocol_link"
Extraction ||--}o FailureCategorization : "has_failure_categorization"
DissolvingProcess ||--|o QuantityValue : "duration"
DissolvingProcess ||--|o QuantityValue : "temperature"
DissolvingProcess ||--}o PortionOfSubstance : "substances_used"
DissolvingProcess ||--}o NamedThing : "has_input"
DissolvingProcess ||--}o ProcessedSample : "has_output"
DissolvingProcess ||--}o Instrument : "instrument_used"
DissolvingProcess ||--|o Protocol : "protocol_link"
DissolvingProcess ||--}o FailureCategorization : "has_failure_categorization"
ChromatographicSeparationProcess ||--}o MobilePhaseSegment : "ordered_mobile_phases"
ChromatographicSeparationProcess ||--|o QuantityValue : "temperature"
ChromatographicSeparationProcess ||--}o NamedThing : "has_input"
ChromatographicSeparationProcess ||--}o ProcessedSample : "has_output"
ChromatographicSeparationProcess ||--}o Instrument : "instrument_used"
ChromatographicSeparationProcess ||--|o Protocol : "protocol_link"
ChromatographicSeparationProcess ||--}o FailureCategorization : "has_failure_categorization"
ChemicalConversionProcess ||--|o QuantityValue : "duration"
ChemicalConversionProcess ||--|o QuantityValue : "temperature"
ChemicalConversionProcess ||--}o PortionOfSubstance : "substances_used"
ChemicalConversionProcess ||--|o QuantityValue : "substances_volume"
ChemicalConversionProcess ||--}o NamedThing : "has_input"
ChemicalConversionProcess ||--}o ProcessedSample : "has_output"
ChemicalConversionProcess ||--}o Instrument : "instrument_used"
ChemicalConversionProcess ||--|o Protocol : "protocol_link"
ChemicalConversionProcess ||--}o FailureCategorization : "has_failure_categorization"

