@startuml
skinparam nodesep 10
class "QuantityValue"
class "Protocol"
class "ProcessedSample"
class "PortionOfSubstance" {
    {field} "sample_state_information": "SampleStateEnum" [opt]
    {field} "substance_role": "SubstanceRoleEnum" [opt]
    {field} "type": "uriorcurie" [req]
}
class "ChemicalEntity" {
    {field} "alternative_names": "string" [0..*]
    {field} "chemical_formula": "string" [opt]
    {field} "inchi": "string" [opt]
    {field} "inchi_key": "string" [opt]
    {field} "smiles": "string" [0..*]
    {field} "id"(i): "uriorcurie" [req]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
class "Extraction" {
    {field} "extraction_target": "ExtractionTargetEnum" [opt]
    {field} "id": "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
class "DissolvingProcess" {
    {field} "id": "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
class "MobilePhaseSegment" {
    {field} "type": "uriorcurie" [req]
}
class "ChemicalConversionProcess" {
    {field} "chemical_conversion_category": "ChemicalConversionCategoryEnum" [opt]
    {field} "id": "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "volume"
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "source_concentration"
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "mass"
"PortionOfSubstance" --> "0..1" "ChemicalEntity" : "known_as"
"PortionOfSubstance" *--> "0..1" "QuantityValue" : "final_concentration"
"Extraction" *--> "0..*" "PortionOfSubstance" : "substances_used"
"DissolvingProcess" *--> "0..*" "PortionOfSubstance" : "substances_used"
"MobilePhaseSegment" *--> "0..*" "PortionOfSubstance" : "substances_used"
"ChemicalConversionProcess" *--> "0..*" "PortionOfSubstance" : "substances_used"
class "OntologyClass"
abstract "NamedThing"
class "ChromatographicSeparationProcess" {
    {field} "has_calibration": "string" [opt]
    {field} "chromatographic_category": "ChromatographicCategoryEnum" [opt]
    {field} "stationary_phase": "StationaryPhaseEnum" [opt]
    {field} "id": "uriorcurie" [req]
    {field} "processing_institution"(i): "ProcessingInstitutionEnum" [opt]
    {field} "start_date"(i): "string" [opt]
    {field} "end_date"(i): "string" [opt]
    {field} "qc_status"(i): "StatusEnum" [opt]
    {field} "qc_comment"(i): "string" [opt]
    {field} "name"(i): "string" [opt]
    {field} "description"(i): "string" [opt]
    {field} "alternative_identifiers"(i): "uriorcurie" [0..*]
    {field} "type"(i): "uriorcurie" [req]
}
"MobilePhaseSegment" *--> "0..1" "QuantityValue" : "volume"
"MobilePhaseSegment" *--> "0..1" "QuantityValue" : "duration"
"ChromatographicSeparationProcess" *--> "0..*" "MobilePhaseSegment" : "ordered_mobile_phases"
class "MetaboliteQuantification"
class "MaterialProcessing"
class "Instrument"
abstract "FluidHandling"
class "FailureCategorization"
class "Database"
"Extraction" --> "1..*" "NamedThing" : "has_output"
"Extraction" *--> "0..1" "QuantityValue" : "volume"
"Extraction" *--> "0..1" "QuantityValue" : "input_mass"
"Database" *--> "0..*" "Extraction" : "extraction_set"
"MaterialProcessing" ^-- "Extraction"
"DissolvingProcess" *--> "0..1" "QuantityValue" : "temperature"
"DissolvingProcess" *--> "0..1" "QuantityValue" : "duration"
"MaterialProcessing" ^-- "DissolvingProcess"
"ChromatographicSeparationProcess" *--> "0..1" "QuantityValue" : "temperature"
"FluidHandling" ^-- "ChromatographicSeparationProcess"
"Database" *--> "0..*" "ChemicalEntity" : "chemical_entity_set"
"MetaboliteQuantification" --> "0..1" "ChemicalEntity" : "metabolite_quantified"
"OntologyClass" ^-- "ChemicalEntity"
"ChemicalConversionProcess" *--> "0..1" "QuantityValue" : "substances_volume"
"ChemicalConversionProcess" *--> "0..1" "QuantityValue" : "temperature"
"ChemicalConversionProcess" *--> "0..1" "QuantityValue" : "duration"
"MaterialProcessing" ^-- "ChemicalConversionProcess"
@enduml
