erDiagram
PortionOfSubstance {
    SampleStateEnum sample_state_information  
    SubstanceRoleEnum substance_role  
    uriorcurie type  
}
QuantityValue {
    float has_maximum_numeric_value  
    float has_minimum_numeric_value  
    double has_numeric_value  
    unit has_unit  
    string has_raw_value  
    uriorcurie type  
}
Solution {
    uriorcurie type  
}
MetaboliteQuantification {
    uriorcurieList alternative_identifiers  
    float highest_similarity_score  
    uriorcurie type  
}
ChromatographicSeparationProcess {
    ChromatographicCategoryEnum chromatographic_category  
    StationaryPhaseEnum stationary_phase  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
FailureCategorization {
    FailureWhatEnum qc_failure_what  
    FailureWhereEnum qc_failure_where  
}
Protocol {
    string url  
    string name  
    uriorcurie type  
}
ChemicalEntity {
    string chemical_formula  
    string inchi  
    string inchi_key  
    stringList smiles  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}
ChemicalConversionProcess {
    ChemicalConversionCategoryEnum chemical_conversion_category  
    ProcessingInstitutionEnum processing_institution  
    string start_date  
    string end_date  
    StatusEnum qc_status  
    string qc_comment  
    uriorcurie id  
    string name  
    string description  
    uriorcurieList alternative_identifiers  
    uriorcurie type  
}

PortionOfSubstance ||--|o QuantityValue : "final_concentration"
PortionOfSubstance ||--|o ChemicalEntity : "known_as"
PortionOfSubstance ||--|o QuantityValue : "mass"
PortionOfSubstance ||--|o QuantityValue : "source_concentration"
PortionOfSubstance ||--|o QuantityValue : "volume"
QuantityValue ||--|o WorkflowExecution : "was_generated_by"
Solution ||--}o PortionOfSubstance : "substances_used"
Solution ||--|o QuantityValue : "volume"
MetaboliteQuantification ||--|o ChemicalEntity : "metabolite_quantified"
ChromatographicSeparationProcess ||--|o DataObject : "has_calibration"
ChromatographicSeparationProcess ||--}o Solution : "ordered_mobile_phases"
ChromatographicSeparationProcess ||--|o QuantityValue : "temperature"
ChromatographicSeparationProcess ||--}o NamedThing : "has_input"
ChromatographicSeparationProcess ||--}o ProcessedSample : "has_output"
ChromatographicSeparationProcess ||--}o Instrument : "instrument_used"
ChromatographicSeparationProcess ||--|o Protocol : "protocol_link"
ChromatographicSeparationProcess ||--}o FailureCategorization : "has_failure_categorization"
ChemicalConversionProcess ||--|o QuantityValue : "duration"
ChemicalConversionProcess ||--|o QuantityValue : "temperature"
ChemicalConversionProcess ||--}o PortionOfSubstance : "substances_used"
ChemicalConversionProcess ||--|o QuantityValue : "substances_volume"
ChemicalConversionProcess ||--}o NamedThing : "has_input"
ChemicalConversionProcess ||--}o ProcessedSample : "has_output"
ChemicalConversionProcess ||--}o Instrument : "instrument_used"
ChemicalConversionProcess ||--|o Protocol : "protocol_link"
ChemicalConversionProcess ||--}o FailureCategorization : "has_failure_categorization"

