[tool.poetry]
name = "nmdc_schema"
version = "0.0.0"
description = "Schema resources for the National Microbiome Data Collaborative (NMDC)"
authors = [
    "Bill Duncan <wdduncan@gmail.com>",
    "Mark Andrew Miller <MAM@lbl.gov>",
    "Sujay Patil <spatil@lbl.gov>",
    "Chris Mungall <cjmungall@lbl.gov>",
]

readme = "README.md"

homepage = "https://microbiomedata.github.io/nmdc-schema/"
repository = "https://github.com/microbiomedata/nmdc-schema"
documentation = "https://microbiomedata.github.io/nmdc-schema/"

keywords = ["NMDC", "schema", "metadata", "microbiome"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
]

packages = [
    { include = "nmdc_schema" }
]

include = [
    "jsonschema/nmdc.schema.json",
    "sssom/gold-to-mixs.sssom.tsv",
    "src/schema/*.yaml"
]

[tool.poetry.scripts]
validate-nmdc-json = "nmdc_schema.validate_nmdc_json:cli"
fetch-nmdc-schema = "nmdc_schema.nmdc_data:get_nmdc_jsonschema"
nmdc-version = "nmdc_schema.nmdc_version:cli"
nmdc-data = "nmdc_schema.nmdc_data:cli"
migrate_3_2_to_7 = "nmdc_schema.migrate_3_2_to_7:cli"

[tool.poetry.dependencies]
python = "^3.9"
linkml-runtime = "^1.3.0"


[tool.poetry.dev-dependencies]
black = "^22.10.0"
build = "^0.9.0"
check-jsonschema = "^0.19.2"
click-log = "^0.4.0"
deepdiff = "^6.2.1"
docutils = "^0.19"
jq = "^1.3.0"
jupyter = "^1.0.0"
linkml = "^1.3.15"
mkdocs = "^1.4.2"
mkdocs-material = "^8.5.7"
mkdocs-mermaid2-plugin = "^0.6.0"
pandas = "^1.5.1"
pendulum = "^2.1.2"
pymongo = "^4.3.3"
python-dotenv = "^0.21.0"
twine = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
