name: artifact-upload-action
on: workflow_dispatch
# wget or curl?! which is noisier
# combine run statements?
# could run some jobs in parallel
jobs:
  artifact-upload-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1.3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - run: make squeaky-clean all test validate-filtered-request-all validate-polymorphic
      - run: date > date.txt
      - uses: actions/upload-artifact@v3
        with:
          name: date file
          path: date.txt
